package me.anno.support.python.runtime

class PythonRuntimeTests {
    // todo test different features, first simple things, later complex things...
    // todo define PyObject and PyNull classes/objects...
    // todo define property getter and setters...
    // todo override our property resolution logic with something general for Python...
    // todo in PythonASTBuilder, resolve local fields immediately, so we can declare them(?)
}